### ISSUE TITLE
topicのnamespace

### ISSUE THREAD

**Issue by H1rono** [rogy-AquaLab/2024_cavolinia#24]
https://github.com/rogy-AquaLab/2024_cavolinia/blob/e5102fe6e5f265efff2c352197c027dd8531255a/device/nucleo_communicate_py/launch/channel_launch.py#L9

ここなど

`s/device/packet/g`(topicだけ)

**Comment by H1rono** [comment]
remapを入れてtopicだけ名前を変える
https://github.com/rogy-AquaLab/2024_cavolinia/blob/a40f5b13540163a617d9b85f57f562234daaabb2/app/power_map/launch/launch.py#L20

**Comment by H1rono** [comment]
- https://design.ros2.org/articles/static_remapping.html
- https://docs.ros.org/en/humble/Tutorials/Intermediate/Launch/Launch-system.html
- https://zenn.dev/uedake/articles/ros2_node3_remap

**Comment by H1rono** [comment]
各README修正も入れたい

**Comment by 23-yoshikawa** [comment]
app/imshow, device/camera_reader
device/joystick 
のlaunchファイルの修正？？

**Comment by H1rono** [comment]
nucleo_communicate_pyも
