### ISSUE TITLE
スラスタの最大出力を下げる

### ISSUE THREAD

**Issue by Chikurin1014** [rogy-AquaLab/2024_cavolinia#71]
1480 ± 150くらい

**Comment by H1rono** [comment]
configをいじればいい

https://github.com/rogy-AquaLab/2024_umiusi/blob/fb19c0a3d37755fac958c8b7f78a11246edf3ac9/app/power_map/config/default_param.yml#L5-L6

で、configでできる以上その目的でリポジトリに変更を加えることはやりたくない
まあ`ul`に何かしらlaunchファイルを増やすくらいはやってもいいかな...

**Comment by Chikurin1014** [comment]
今のデフォルト値が破壊的な強さなので、デフォルト値から下げてもらいたいです
